CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
isAdmin BOOLEAN DEFAULT FALSE,
address_1 VARCHAR(100),
address_2 VARCHAR(100),
email VARCHAR(50) UNIQUE NOT NULL,
pass VARCHAR(255) NOT NULL,
createdAt TIMESTAMP DEFAULT NOW());